title: "Bug: "
labels: ["bug", "NEED_TO_LABEL"]

body:
- type: checkboxes
  id: "checks"
  attributes:
    label: "Checks"
    options:
    - label: "I ran `cw doctor` in the affected command line session and it didn't resolve my issue"
      required: true
    - label: "I ran `cw restart` and it didn't resolve my issue"
      required: true
    - label: "I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue"
      required: true
    
- type: textarea
  id: "expected"
  attributes:
    label: "Expected behaviour"
    description: "What did you expect to happen?"
  validations:
    required: true
    
- type: textarea
  id: "actual"
  attributes:
    label: "Actual behaviour"
    description: "What actually happened? Please provide a screenshot or video if possible."
  validations:
    required: true

- type: textarea
  id: "reproduce"
  attributes:
    label: "Steps to reproduce"
    description: "Are you able to reproduce this issue? If so, how?"

- type: textarea
  id: "environment"
  attributes:
    label: "Environment"
    description: "If possible, run `cw diagnostic` and paste the information below"
    render: yaml
